=encoding utf8

=head1 NAME

Acme::AjiFry - AjiFry Language (アジフライ語) Translator


=head1 VERSION

This document describes Acme::AjiFry version 0.08


=head1 SYNOPSIS

    use Acme::AjiFry;
    use Acme::AjiFry::EN;

    my $ajifry = Acme::AjiFry->new();
    my $ajifry_en = Acme::AjiFry::EN->new();

    print $ajifry->translate_to_ajifry('おさしみ')."\n"; # outputs => "食えアジフライお刺身食え食えお刺身ドボドボ岡星ドボドボ"
    print $ajifry->translate_from_ajifry('食えアジフライお刺身食え食えお刺身ドボドボ岡星ドボドボ')."\n"; # outputs => "おさしみ"

    print $ajifry_en->translate_to_ajifry('012abcABC!!!')."\n"; # outputs => '京極お刺身京極むむ･･･京極アジフライ食え食え食え食えドボドボ食えお刺身山岡ドボドボ山岡お刺身山岡むむ･･･!!!'
    print $ajifry_en->translate_from_ajifry('京極お刺身京極むむ･･･京極アジフライ食え食え食え食えドボドボ食えお刺身山岡ドボドボ山岡お刺身山岡むむ･･･!!!')."\n"; # outputs => '012abcABC!!!'


=head1 SYNOPSIS for Acme::AjiFry::Perl

Before execute

    use Acme::AjiFry::Perl;

    print 'hello';

After execute

    use Acme::AjiFry::Perl;

    アジ食え食えアジお刺身フライむむ･･･お刺身むむ･･･アジアジフライ中川'フライお刺身食えアジフライお刺身ドボドボお刺身ドボドボお刺身アジフライ';


=head1 DESCRIPTION

Acme::AjiFry, Acme::AjiFry::EN and Acme::AjiFry::Perl are AjiFry-Language translator.

Acme::AjiFry can translate Japanese into AjiFry-Language, and vice versa. Acme::AjiFry::EN can translate English into AjiFry-Language. Acme::AjiFry::Perl rewrites your perl script which use this module by AjiFru-Language.

If you would like to know about AjiFry-Language, please refer to the folowing web site (Japanese Web Site).
L<http://ja.uncyclopedia.info/wiki/%E3%82%A2%E3%82%B8%E3%83%95%E3%83%A9%E3%82%A4%E8%AA%9E>


=head1 DEPENDENCIES

Perl 5.10.0 or later.

Class::Accessor::Fast 0.34 or later.

Filter::Simple 0.84 or later.

=head1 BUGS AND LIMITATIONS

=for author to fill in:
A list of known problems with the module, together with some
indication Whether they are likely to be fixed in an upcoming
release. Also a list of restrictions on the features the module
does provide: data types that cannot be handled, performance issues
and the circumstances in which they may arise, practical
limitations on the size of data sets, special cases that are not
(yet) handled, etc.

No bugs have been reported.

Please report any bugs or feature requests to
C<bug-acme-ajifry@rt.cpan.org>, or through the web interface at
L<http://rt.cpan.org>.


=head1 AUTHOR

moznion  C<< <moznion[at]gmail.com> >>


=head1 LICENCE AND COPYRIGHT

Copyright (c) 2012, moznion C<< <moznion[at]gmail.com> >>. All rights reserved.

This module is free software; you can redistribute it and/or
modify it under the same terms as Perl itself. See L<perlartistic>.
